name: Secrets and Environment Variables

on:
  push:
    branches: [ main ]

jobs:
  default-env-variables-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Secrets
        run: echo "My existing secret is ${{ secrets.API_KEY }}"
