name: Secrets and Environment Variables

on:
  push:
    branches: [ main ]

jobs:
  top-secret-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      APIKEY: ${{ secrets.API_KEY }}
